-- Roxlier Store Rating System - Database Schema

-- Create Database
CREATE DATABASE IF NOT EXISTS roxlier_db;
USE roxlier_db;

-- USERS TABLE
DROP TABLE IF EXISTS users;
CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role ENUM('user','owner','admin') DEFAULT 'user',
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- STORES TABLE
DROP TABLE IF EXISTS stores;
CREATE TABLE stores (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(200) NOT NULL,
  address VARCHAR(255),
  ownerId INT,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (ownerId) REFERENCES users(id) ON DELETE SET NULL
);

-- RATINGS TABLE
DROP TABLE IF EXISTS ratings;
CREATE TABLE ratings (
  id INT AUTO_INCREMENT PRIMARY KEY,
  ratingValue INT NOT NULL CHECK (ratingValue BETWEEN 1 AND 5),
  userId INT NOT NULL,
  storeId INT NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (storeId) REFERENCES stores(id) ON DELETE CASCADE
);

-- Insert Admin User for Testing

INSERT INTO users (name, email, password, role)
VALUES ('Admin', 'admin@gmail.com',
'$2a$10$ZYx0sLLYdVh9MuNoMNFcQOFKuvsYQXzJN9WfzgRuTEq9hF8PVVxHS', 'admin');
-- Password = 123456

